### ISSUE TITLE
Some icon images are corrupted in the Github download version

### ISSUE THREAD

**Issue by cw-kid** [gderosa/xbmc-vera#5]
Hi

For some reason when you download this add-on from GitHub on the Internet the icons are corrupted in certain folders. I managed to find working icons in one folder and I then copied these files to another folder where the icons were corrupted. The result is I can now see the icons in XBMC OK!

Images appear to be corrupt in the following folders:

xbmc-vera-0.1.2\resources\skins\Default\media\controls
xbmc-vera-0.1.2\resources\skins\Default\media\devices

The images appear to be OK in these folders:

xbmc-vera-0.1.2\resources\skins\Default\media\mios\www\cmh\skins\default\icons
xbmc-vera-0.1.2\resources\skins\Default\media\mios\www\cmh\skins\default\images\devices

**Comment by cw-kid** [comment]
Possible Feature Request - Would be to be able to choose and use different icon images ?

**Comment by gderosa** [comment]
@cw-kid, in what OS do you find this issue?

The images you find corrupt are actually symlinks to `../mios/www/cmh/skins/default/`... etc. i.e. the directory where images look not corrupted (where they are in fact regular files, not symbolic links).

The backslash in your paths make me think you're on Windows... Right, Unix symlinks won't work on Windows :-( and this explains the root cause of the issue.

The reason I put some images in a separate directory is copyright: thay are just copied from (and credited to) the Vera web UI, they belong to Vera/Micasaverde/MiOS, not to Kodi nor to xbmc-vera authors.

However, I'll find a solution with no use of symlinks to ensure Windows portability.

**Comment by gderosa** [comment]
@cw-kid , should be fixed now. https://github.com/gderosa/xbmc-vera/pull/13.
